### ISSUE TITLE
Repository is Null

### ISSUE THREAD

**Issue by mustafamizrak** [icougil/FilmRecommendationService#1]

**Comment by icougil** [comment]
Hi Mustafa.

What do you mean by this? In the production code? Yes, it is `null` and it could be solved by creating a `Datasource` and passing it through the constructor to the repository (as it has been done in the test code). I leaved it like this just an example, because how this Datasource will be injected, could be different in real Production code, for example, it could come from another source, not from a TestContainer instance but probably from a real connection to a Database and therefore you may need a DB running in local or something similar...

What do you suggest? We can finish with a similar approach for example, providing a docker image (and therefore you may need to build & run it before) where we can connect to in local?

**Comment by mustafamizrak** [comment]
Hi,

I hope that the yesterday presentation/demo (Brown Bag Lunch) coded are placed here. That is why I create a `null` issue.

Regards,

**Comment by icougil** [comment]
Yes, the point if you remember, is that I demonstrated that the test was working.

So, if we talking about the test, it is not working from you then? I double-checked and it is still working for me.

Have you verified for example that the integration test already pulled the _postgres_ image from Docker hub and it was started successfully ?

Can you verify that when you run the integration test you can see a new docker container is running in your environment?

**Comment by icougil** [comment]
Hi Mustafa,

Have you found some time to check if it's working for you? 

Best,

**Comment by mustafamizrak** [comment]
Hi, I coud not found the codes (your unit test examples etc.). Could you share the link/url? Then I can run and  I contribute with the real DB.
Regards,

**Comment by icougil** [comment]
Aaaah I see your issue now!

Have a look at the "a_solution" branch then 😉

**Comment by icougil** [comment]
I guess I can close the issue now ;-)
